# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
#  the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.



def find_even_values_sum_in_fib_seq(n : int) -> int:
    a, b = 1, 2
    total = 0
    while a <= n:
        if a % 2 == 0:
            total += a
        a, b = b, a + b
    return total

def main():
    four_million = 4 * (10 ** 6)
    print(find_even_values_sum_in_fib_seq(four_million))


if __name__ == '__main__':
    main()
